name: Run Azure CLI Login with OpenID Connect
on: [push]

permissions:
  id-token: write
  contents: read


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
     
jobs: 
  test:
    runs-on: self-hosted
    steps:
    - name: Install Azure CLI
      shell: powershell
      run: |
          $az_installed = Get-Command az -ErrorAction SilentlyContinue
          if (-not $az_installed) {
            Write-Host "Azure CLI not found. Installing..."
            $msiUrl = "https://aka.ms/installazurecliwindowsx64"
            $outPath = "$env:TEMP\azure-cli.msi"
            Invoke-WebRequest -Uri $msiUrl -OutFile $outPath
            Start-Process msiexec.exe -Wait -ArgumentList "/I $outPath /quiet /norestart"
            # Refresh the path for the current session
            $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          } else {
            Write-Host "Azure CLI is already installed."
          }

    - name: Verify Installation
      run: az --version
    - name: Azure CLI Login
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v3
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          
