name: Run Azure CLI Login with OpenID Connect
on:
  push:
    branches:
      - dev
      - prod

permissions:
  id-token: write
  contents: read


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
     
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
        
    # - name: Terraform Init & App
    #   working-directory: terraform/environments/{{ env.ENV }}
    #   run: |
    #     terraform init
    #     terraform apply -auto-approve
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure CLI Login
      uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build & Push Docker Image
      run: |
        az acr login --name crflask${ENV}
        docker build -t flask_image:${ENV} ./app
        docker tag flask_image:${ENV} crflask${ENV}.azurecr.io/flask_image:${ENV}
        docker push crflask${ENV}.azurecr.io/flask_image:${ENV}

    - name: Deploy to AKS
      run: |
        az aks get-credentials \
          --resource-group rg-${ENV} \
          --name aks-flask${ENV} \
          --overwrite-existing

        kubectl apply -f k8s/
        kubectl get svc flask-app-service


          
